# .github/workflows/cici-workflow.yml

name: CICI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CCACHE_DIR: ./ccache
  MAKEFLAGS: -j2

jobs:
  build:
    name: Build OpenCog Components
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install necessary system packages
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git libssl-dev libpq-dev

      # Step 3: Set environment variables
      - name: Set Environment Variables
        run: |
          echo "CCACHE_DIR=${CCACHE_DIR}" >> $GITHUB_ENV
          echo "MAKEFLAGS=${MAKEFLAGS}" >> $GITHUB_ENV

      # Step 4: Clone and build cogutil
      - name: Clone cogutil
        run: |
          git clone --depth 1 https://github.com/opencog/cogutil ./cogutil

      - name: Build cogutil
        run: |
          mkdir -p ./cogutil/build
          cd ./cogutil/build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      # Step 5: Clone and build atomspace
      - name: Clone atomspace
        run: |
          git clone --depth 1 https://github.com/opencog/atomspace ./atomspace

      - name: Build atomspace
        run: |
          mkdir -p ./atomspace/build
          cd ./atomspace/build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      # Step 6: Clone and build cogserver
      - name: Clone cogserver
        run: |
          git clone --depth 1 https://github.com/opencog/cogserver ./cogserver

      - name: Build cogserver
        run: |
          mkdir -p ./cogserver/build
          cd ./cogserver/build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      # Step 7: Clone and build attention
      - name: Clone attention
        run: |
          git clone --depth 1 https://github.com/opencog/attention ./attention

      - name: Build attention
        run: |
          mkdir -p ./attention/build
          cd ./attention/build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      # Step 8: Clone and build unify
      - name: Clone unify
        run: |
          git clone --depth 1 https://github.com/opencog/unify ./unify

      - name: Build unify
        run: |
          mkdir -p ./unify/build
          cd ./unify/build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      # Step 9: Clone and build ure
      - name: Clone ure
        run: |
          git clone --depth 1 https://github.com/opencog/ure ./ure

      - name: Build ure
        run: |
          mkdir -p ./ure/build
          cd ./ure/build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      # Step 10: Clone and build miner
      - name: Clone miner
        run: |
          git clone --depth 1 https://github.com/opencog/miner ./miner

      - name: Build miner
        run: |
          mkdir -p ./miner/build
          cd ./miner/build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      # Step 11: Clone and build asmoses
      - name: Clone asmoses
        run: |
          git clone --depth 1 https://github.com/opencog/asmoses ./asmoses

      - name: Build asmoses
        run: |
          mkdir -p ./asmoses/build
          cd ./asmoses/build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      # Step 12: Clone and build opencog
      - name: Clone opencog
        run: |
          git clone --depth 1 https://github.com/opencog/opencog ./opencog

      - name: Build opencog
        run: |
          mkdir -p ./opencog/build
          cd ./opencog/build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      # Step 13: Clone and build package
      - name: Clone package
        run: |
          git clone --depth 1 https://github.com/opencog/package ./package

      - name: Build package
        run: |
          mkdir -p ./package/build
          cd ./package/build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      # Step 14: Run tests for opencog
      - name: Run Tests
        run: |
          cd ./opencog/build
          make check ARGS="$MAKEFLAGS"

      # Step 15: Print test log
      - name: Print Test Log
        if: always()
        run: |
          cat ./opencog/build/tests/Testing/Temporary/LastTest.log

      # Step 16: Build Debian package
      - name: Build Debian Package
        run: |
          cd ./cogutil/build
          make package

      # Step 17: Upload package artifacts
      - name: Upload Package Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./cogutil/build/packages/
